<?php
/** @var Amasty\RusDolModule\Block\Email\Blacklist $block */
?>

<h2 style="text-align: center">Amasty RusDolModule BlackList Product</h2>
<img style="max-width: 150px; display: block; margin: 0 auto" src="https://pbs.twimg.com/media/E4EPiE4XoAEMRKn.jpg"/>
<div style="text-align: center">
    <p>Sku товара: <?= $block->getBlacklistProduct()->getSku() ?></p>
    <p>Qty товара: <?= $block->getBlacklistProduct()->getQty() ?></p>
</div>

