<div class="timer" data-bind="scope: 'timer'">
    <!-- ko template: getTemplate() --> <!-- /ko -->
</div>

<script type="text/x-magento-init">
    {
        "*": {
                "Magento_Ui/js/core/app": {
                    "components": {
                        "timer": {
                            "component": "Amasty_RusDolModule/js/timer",
                            "template": "Amasty_RusDolModule/timer"
                        }
                    }
                }
            }
    }

</script>
