<p>Здeeсь будетт (а может и нет) timer, который я сделать в другом задании!</p>

<div class="search-widget">
    <input id="search-inp" type="text" placeholder="Search...">
    <ul class="search-result-list"></ul>
</div>

<script type="text/x-magento-init">
   {
       ".search-widget": {
           "Amasty_RusDolModule/js/widget": {
                "minChars": 3
           }
       }
   }
</script>
