<?php
/** @var Amasty\RusDolModule\Block\Index $block */
?>

<form name="form" class="<?= $block->getData('rus-form') ?>"
      action="<?= $block->getUrl('ruslan/cart/add') ?>" method="GET"
      data-mage-init='{"validation": {}}'>
    <div class="fields-wrap">
        <div class="<?= $block->getData('inp-sku') ?>" data-bind="scope: 'autocomplete'">
            <!-- ko template: getTemplate() --> <!-- /ko -->
        </div>
        <?php if ($block->isShowQty()) { ?>
            <div class="<?= $block->getData('inp-qty') ?>">
                <label for="qty">Введите QTY:</label>
                <input type="number" name="qty" placeholder="Ваш QTY" id="qty"
                       data-validate='{"required": true, "integer": true, "validate-greater-than-zero": true}'
                       value="<?= $block->getQtyValue() ?>">
            </div>
        <?php }; ?>
    </div>
    <div class="btn-container">
        <button type="submit" class="<?= $block->getData('btn-sbm') ?>">
            Отправить
        </button>
    </div>
    <?= $block->getChildHtml('amasty_rusdolmodule.additional') ?>
</form>

<script type="text/x-magento-init">
    {
        "*": {
                "Magento_Ui/js/core/app": {
                    "components": {
                        "autocomplete": {
                            "component": "Amasty_RusDolModule/js/autocomplete",
                            "template": "Amasty_RusDolModule/autocomplete"
                        }
                    }
                }
            }
    }

</script>
